# Generated by Django 4.1.13 on 2024-04-09 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('launch_time', models.TimeField()),
                ('available_tickets', models.IntegerField()),
                ('ticket_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('finished', 'Finished')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('movies', 'Movies'), ('games', 'Games'), ('parties', 'Parties'), ('art', 'Art'), ('meet', 'Meet'), ('music', 'Music'), ('education', 'Education')], max_length=100, null=True)),
                ('age_category', models.CharField(blank=True, choices=[('child', 'Child (0-12 years)'), ('teen', 'Teen (13-19 years)'), ('young_adult', 'Young Adult (20-39 years)'), ('adult', 'Adult (40-59 years)'), ('senior', 'Senior (60+ years)'), ('everyone', 'family')], max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('people_attending', models.ManyToManyField(blank=True, related_name='events_attending', to='user.user')),
            ],
        ),
    ]
