# Generated by Django 4.1.13 on 2024-04-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer_contact',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_link',
        ),
    ]
