# Generated by Django 4.1.13 on 2024-04-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_deadline_remove_event_organizer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_category',
            field=models.CharField(blank=True, choices=[('child', 'Child (0-12 years)'), ('teen', 'Teen (13-19 years)'), ('young_adult', 'Young Adult (20-39 years)'), ('adult', 'Adult (40-59 years)'), ('senior', 'Senior (60+ years)'), ('everyone', 'family')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('movies', 'Movies'), ('games', 'Games'), ('parties', 'Parties'), ('art', 'Art'), ('meet', 'Meet'), ('music', 'Music'), ('education', 'Education')], max_length=100, null=True),
        ),
    ]
