# Generated by Django 4.1.13 on 2024-04-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150, unique=True)),
                ('password', models.CharField(default='', max_length=128)),
                ('age', models.PositiveIntegerField(null=True)),
                ('field_of_interest', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('governorate', models.CharField(max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('cart', models.JSONField()),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret_key', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
