# Generated by Django 4.1.13 on 2024-04-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.JSONField(),
        ),
    ]
